### ISSUE TITLE
font monospace doesn't work on Windows PC

### ISSUE THREAD

**Issue by fritx** [fritx/blog#7]
``` css
/* in Chrome, this built-in style makes no effect */
tt, code, kbd, samp {   /* user agent stylesheet */
    font-family: monospace;
}
```

``` css
/* starts to work with the patch below */
code {
  font-family: monospace, monospace;
}
```

maybe good to include the entire https://github.com/necolas/normalize.css

``` css
/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

code,
kbd,
pre,
samp {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}
```
